### ISSUE TITLE
overlap_features.py: IDF needs correction, needs stopping before stemming

### ISSUE THREAD

**Issue by gauravbaruah** [castorini/data#8]
1) **Wrong IDF**
The compute_dfs() function in line 110 has "/=" instead of "=".
This makes the IDF for a term t to be n_t / log(N/n_t) [Wrong].
Should be changed to " = log(N/(1+n_t))"

2) **Stopping after Stemming**
Once words are down to their stems, they may not match the words in the stoplist. Stopping will not be as effective as it should be. 
function load_data() stems first, and then stopping is done in compute_overlap_features().
Stopping should be done before stemming.

**Comment by gauravbaruah** [comment]
This Bug is from the original SM paper. Code link is
https://github.com/aseveryn/deep-qa/blob/249a1ec14ef980a5630b1a2dccf5f587245e16e1/parse.py#L123

**Comment by gauravbaruah** [comment]
https://github.com/aseveryn/deep-qa/blob/249a1ec14ef980a5630b1a2dccf5f587245e16e1/parse.py#L123

**Comment by hatianzhang** [comment]
From original SM paper: This feature vector contains only four features: word overlap and IDF-weighted word overlap computed between all words and only non-stop words.

The feature they used is IDF weighed word overlap features. Not just idf features.

So I think it is not a bug.
